=== pageseeder/ox/pso-ox-core/src/main/resources/library/model-1.0.dtd
<!--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-->
<!--                                                                        -->
<!-- Title:         OX DTD for model configuration file                     -->
<!-- System:        OX                                                      -->
<!-- Status:        Beta 2                                                  -->
<!-- Description:   A schema for the defining the OX model                  -->
<!-- Version:       1.0                                                     -->
<!-- LastModified:  19 October 2016                                         -->
<!-- Author(s):     Christophe Lauret                                       --> 
<!--                Ciber Cai                                               -->
<!--                                                                        -->
<!--;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-->



<!ELEMENT pipelines       (pipeline+ )                                   >
<!ATTLIST pipelines       version         CDATA     #FIXED        "1.0"  
                          processors      CDATA     #IMPLIED             >


<!ELEMENT pipeline        (step+ )                                       >
<!ATTLIST pipeline        name            CDATA     #REQUIRED 
                          description     CDATA     #IMPLIED
                          accepts         CDATA     #IMPLIED             >

<!ELEMENT step            (parameter* )                                  >
<!ATTLIST step            id              CDATA     #REQUIRED 
                          name            CDATA     #IMPLIED 
                          class           CDATA     #REQUIRED            
                          callback        CDATA     #IMPLIED             >

<!ELEMENT parameter                                 EMPTY                >
<!ATTLIST parameter       name            CDATA     #REQUIRED
                          value           CDATA     #REQUIRED            >
                          
<!ELEMENT output                                    EMPTY                > 
<!ATTLIST output          file            CDATA     #IMPLIED
                          folder          CDATA     #IMPLIED             >

=== pageseeder/ox/pso-ox-psml/src/test/resources/org/pageseeder/ox/psml/step/validate/models/test/model.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pipelines PUBLIC "-//PageSeeder//DTD::OX model 1.0//EN"
                            "http://www.pageseeder.org/schema/ox/model-1.0.dtd">
<pipelines icon="engine" >

  <pipeline id="test-pipeline" name="Test Pipeline"
            description="The sample pipeline will test"
            accepts="application/vnd.pageseeder.psml+xml" default="true">


    <step id="validate-char" name="Characters validation" class="org.pageseeder.ox.psml.step.Validate">
      <parameter name="type"   value="characters" />
      <parameter name="output" value="psml-reports/characters-report.psml" />
    </step>
    <step id="validate-wf" name="Simple XML validation" class="org.pageseeder.ox.psml.step.Validate">
      <parameter name="type"   value="well-formed" />
      <parameter name="output" value="psml-reports/wellformed-report.psml" />
    </step>
    <step id="validate-xsd" name="Schema validation" class="org.pageseeder.ox.psml.step.Validate">
      <parameter name="type"   value="schema" />
      <parameter name="output" value="psml-reports/schema-report.psml" />
    </step>
    <step id="validate-sch" name="Schematron validation" class="org.pageseeder.ox.psml.step.Validate">
      <parameter name="type"   value="schematron" />
      <parameter name="output" value="psml-reports/schematron-report.psml" />
    </step>
  </pipeline>
</pipelines>
